#! /bin/bash

# HISTCONTROL='ignoreboth'
HISTTIMEFORMAT='[%Y-%m-%d %H:%M:%S] '
HISTFILESIZE=10000
HISTSIZE="\$HISTFILESIZE"

if [[ -d "$HOME/.local/bin" ]]
then
  PATH="$PATH:$HOME/.local/bin"
fi

# vim
export EDITOR=vim
alias vi=vim
